export const GOUVERNORATS = [
    "Ariana",
    "Béja",
    "Ben Arous",
    "Bizerte",
    "Gabès",
    "Gafsa",
    "Jendouba",
    "Kairouan",
    "Kasserine",
    "Kébili",
    "Le Kef",
    "Mahdia",
    "La Manouba",
    "Médenine",
    "Monastir",
    "Nabeul",
    "Sfax",
    "Sidi Bouzid",
    "Siliana",
    "Sousse",
    "Tataouine",
    "Tozeur",
    "Tunis",
    "Zaghouan"
];

export const VILLES_BY_GOUVERNORAT = {
    "Ariana": ["Ariana Ville", "Ettadhamen", "Raoued", "Soukra"],
    "Béja": ["Béja Nord", "Béja Sud", "Medjez el-Bab"],
    "Ben Arous": ["Ben Arous", "Radès", "Ezzahra", "Hammam-Lif"],
    "Bizerte": ["Bizerte", "Mateur", "Ras Jebel"],
    "Gabès": ["Gabès Ville", "Mareth", "Métouia"],
    "Gafsa": ["Gafsa Ville", "Metlaoui", "Redeyef"],
    "Jendouba": ["Jendouba", "Tabarka", "Bou Salem"],
    "Kairouan": ["Kairouan Ville", "Sbikha", "Haffouz"],
    "Kasserine": ["Kasserine Ville", "Fériana", "Sbeitla"],
    "Kébili": ["Kébili Ville", "Douz", "Souk Lahad"],
    "Le Kef": ["Le Kef Ville", "Tajerouine", "Dahmani"],
    "Mahdia": ["Mahdia Ville", "Chebba", "Ksour Essef"],
    "La Manouba": ["Manouba", "Douar Hicher", "Mornaguia"],
    "Médenine": ["Médenine Ville", "Djerba", "Zarzis"],
    "Monastir": ["Monastir Ville", "Sahline", "Ksar Hellal"],
    "Nabeul": ["Nabeul Ville", "Hammamet", "Kelibia"],
    "Sfax": ["Sfax Ville", "El Amra", "Mahrès"],
    "Sidi Bouzid": ["Sidi Bouzid Ville", "Regueb", "Jilma"],
    "Siliana": ["Siliana Ville", "El Krib", "Gaâfour"],
    "Sousse": ["Sousse Ville", "Akouda", "Hammam Sousse"],
    "Tataouine": ["Tataouine Ville", "Ghomrassen", "Remada"],
    "Tozeur": ["Tozeur Ville", "Nefta", "Degache"],
    "Tunis": ["Tunis Centre", "Le Bardo", "La Marsa"],
    "Zaghouan": ["Zaghouan Ville", "El Fahs", "Bir Mcherga"],
};
