export const PROFESSIONS = [
    'Agriculteurs / Artisans',
    'Commerçant',
    'Chef d\'entreprise',
    'Profession libérale',
    'Cadre supérieur',
    'Cadre moyen',
    'Enseignant, Professeur, professions scientifiques',
    'Ingénieurs / Cadre technique d\'entreprise',
    'Technicien / Agent de maîtrise',
    'Policier / militaire',
    'Fonction publique',
    'Employés administratifs d\'entreprise',
    'Ouvriers / Chauffeur',
    'Femme au foyer',
    'Elèves, étudiants',
    'Sans emploi',
    'Autres',
];
